import { create } from 'zustand'
import type { Agent } from '@/types'

const initialAgents: Agent[] = [
  {
    id: 'chairman',
    name: '董事长',
    role: 'CEO / 最高决策者',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '决策层',
  },
  {
    id: 'cto',
    name: '技术总监',
    role: 'CTO / 技术负责人',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '决策层',
  },
  {
    id: 'pm',
    name: '产品经理',
    role: 'Product Manager',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '产品部',
  },
  {
    id: 'analyst',
    name: '分析员',
    role: 'Business Analyst',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '产品部',
  },
  {
    id: 'ux-designer',
    name: 'UX设计师',
    role: 'UX/UI Designer',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '设计部',
  },
  {
    id: 'ui-designer',
    name: 'UI设计师',
    role: 'UI Designer',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '设计部',
  },
  {
    id: 'arch',
    name: '架构师',
    role: 'System Architect',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '技术部',
  },
  {
    id: 'tech-lead',
    name: '技术主管',
    role: 'Tech Lead',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '技术部',
  },
  {
    id: 'coder-1',
    name: '代码员小绿',
    role: '前端工程师',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '技术部',
  },
  {
    id: 'coder-2',
    name: '代码员小蓝',
    role: '后端工程师',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '技术部',
  },
  {
    id: 'coder-3',
    name: '代码员小紫',
    role: '全栈工程师',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '技术部',
  },
  {
    id: 'coder-4',
    name: '代码员小青',
    role: '测试工程师',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '技术部',
  },
  {
    id: 'coder-5',
    name: '代码员小橙',
    role: '数据库工程师',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '技术部',
  },
  {
    id: 'devops',
    name: '运维工程师',
    role: 'DevOps Engineer',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '技术部',
  },
  {
    id: 'inspector-1',
    name: '检查员甲',
    role: '代码审查员',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '质量部',
  },
  {
    id: 'inspector-2',
    name: '检查员乙',
    role: '质量保证员',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '质量部',
  },
  {
    id: 'qa-lead',
    name: '测试主管',
    role: 'QA Lead',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '质量部',
  },
  {
    id: 'expander',
    name: '扩展员',
    role: '战略规划师',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '战略部',
  },
  {
    id: 'researcher',
    name: '研究员',
    role: 'AI Researcher',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '研发部',
  },
  {
    id: 'data-scientist',
    name: '数据科学家',
    role: 'Data Scientist',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '研发部',
  },
  {
    id: 'packer',
    name: '打包员',
    role: '构建工程师',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '运维部',
  },
  {
    id: 'deliverer',
    name: '输送员',
    role: '部署工程师',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '运维部',
  },
  {
    id: 'doc-writer',
    name: '文档工程师',
    role: 'Technical Writer',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '文档部',
  },
  {
    id: 'hr',
    name: '人事专员',
    role: 'HR Specialist',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '人事部',
  },
  {
    id: 'finance',
    name: '财务专员',
    role: 'Finance Specialist',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '财务部',
  },
  {
    id: 'marketing',
    name: '市场专员',
    role: 'Marketing Specialist',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '市场部',
  },
  {
    id: 'customer-service',
    name: '客服专员',
    role: 'Customer Service',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '客服部',
  },
  {
    id: 'security',
    name: '安全工程师',
    role: 'Security Engineer',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '安全部',
  },
  {
    id: 'legal',
    name: '法务顾问',
    role: 'Legal Counsel',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '法务部',
  },
  {
    id: 'sys-admin',
    name: '系统管理员',
    role: 'System Admin',
    status: 'idle',
    progress: 0,
    currentTask: '',
    lastActive: Date.now(),
    department: '运维部',
  },
]

interface AgentState {
  agents: Agent[]
  updateAgentStatus: (id: string, status: Agent['status']) => void
  setAgentProgress: (id: string, progress: number, currentTask?: string) => void
  resetAllAgents: () => void
}

export const useAgentStore = create<AgentState>((set) => ({
  agents: initialAgents,
  updateAgentStatus: (id, status) =>
    set((state) => ({
      agents: state.agents.map((agent) =>
        agent.id === id ? { ...agent, status, lastActive: Date.now() } : agent
      ),
    })),
  setAgentProgress: (id, progress, currentTask) =>
    set((state) => ({
      agents: state.agents.map((agent) =>
        agent.id === id
          ? {
              ...agent,
              progress,
              currentTask: currentTask ?? agent.currentTask,
              lastActive: Date.now(),
            }
          : agent
      ),
    })),
  resetAllAgents: () =>
    set({
      agents: initialAgents.map((agent) => ({
        ...agent,
        status: 'idle',
        progress: 0,
        currentTask: '',
        lastActive: Date.now(),
      })),
    }),
}))
