import { KnowledgePoint } from './knowledgeEngine';

function generateId(): string {
  return Date.now().toString(36) + Math.random().toString(36).substr(2, 9);
}

const now = new Date().toISOString();

export const extendedKnowledge: KnowledgePoint[] = [
  {
    id: generateId(),
    title: 'React useState Hook 使用',
    content: 'useState 是 React 中用于管理组件状态的 Hook。调用 useState 会返回一个状态值和一个更新函数。初始值只在组件首次渲染时生效。',
    source: 'React Docs',
    tags: ['react', 'hooks', 'usestate', '状态管理'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 9,
    references: ['https://react.dev/reference/react/useState']
  },
  {
    id: generateId(),
    title: 'React useEffect 依赖数组',
    content: 'useEffect 的依赖数组决定了何时执行副作用。空数组 [] 表示只在挂载时执行一次；不传依赖数组表示每次渲染都执行；传入特定值则只在这些值变化时执行。',
    source: 'React Docs',
    tags: ['react', 'hooks', 'useeffect', '副作用'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 9,
    references: ['https://react.dev/reference/react/useEffect']
  },
  {
    id: generateId(),
    title: 'TypeScript 泛型函数',
    content: '泛型函数允许在函数参数和返回值之间建立类型关系。使用 <T> 语法定义泛型参数，例如 function identity<T>(arg: T): T { return arg; }',
    source: 'TypeScript Docs',
    tags: ['typescript', '泛型', '函数'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://www.typescriptlang.org/docs/handbook/2/generics.html']
  },
  {
    id: generateId(),
    title: 'Vue3 Composition API ref',
    content: 'ref 用于创建响应式引用，适用于基本类型。通过 .value 访问和修改值，模板中自动解包。例如 const count = ref(0); count.value++',
    source: 'Vue Docs',
    tags: ['vue', 'composition', 'ref', '响应式'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 9,
    references: ['https://vuejs.org/api/reactivity-core.html#ref']
  },
  {
    id: generateId(),
    title: 'Vue3 reactive',
    content: 'reactive 用于创建响应式对象，适用于复杂类型。直接访问属性无需 .value，但不能重新赋值整个对象。例如 const state = reactive({ count: 0 }); state.count++',
    source: 'Vue Docs',
    tags: ['vue', 'composition', 'reactive', '响应式'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://vuejs.org/api/reactivity-core.html#reactive']
  },
  {
    id: generateId(),
    title: 'JavaScript Promise 链式调用',
    content: 'Promise 链式调用使用 .then() 处理成功结果，.catch() 处理错误，.finally() 无论成功失败都会执行。链式调用会按顺序执行。',
    source: 'MDN',
    tags: ['javascript', 'promise', 'async', '异步'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 9,
    references: ['https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise']
  },
  {
    id: generateId(),
    title: 'async/await 错误处理',
    content: '使用 try/catch 包裹 await 调用可以捕获异步错误。也可以使用 .catch() 在 await 表达式后直接捕获。避免未处理的 Promise 拒绝。',
    source: 'MDN',
    tags: ['javascript', 'async', 'await', '错误处理'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function']
  },
  {
    id: generateId(),
    title: 'CSS Flexbox 主轴与交叉轴',
    content: 'Flexbox 有主轴(main axis)和交叉轴(cross axis)。flex-direction 决定主轴方向。justify-content 控制主轴对齐，align-items 控制交叉轴对齐。',
    source: 'CSS-Tricks',
    tags: ['css', 'flexbox', '布局'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://css-tricks.com/snippets/css/a-guide-to-flexbox/']
  },
  {
    id: generateId(),
    title: 'CSS Grid 网格布局',
    content: 'CSS Grid 使用 grid-template-columns 和 grid-template-rows 定义网格轨道。使用 grid-column 和 grid-row 控制元素位置。fr 单位表示剩余空间的比例。',
    source: 'CSS-Tricks',
    tags: ['css', 'grid', '布局'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://css-tricks.com/snippets/css/complete-guide-grid/']
  },
  {
    id: generateId(),
    title: 'Git 分支管理策略',
    content: '常用 Git 分支策略包括 Git Flow 和 Trunk Based Development。Git Flow 使用 develop、feature、release、hotfix 分支；Trunk Based 使用主干分支配合短生命周期特性分支。',
    source: 'Atlassian',
    tags: ['git', '分支', '版本控制'],
    category: '工具链',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://www.atlassian.com/git/tutorials/comparing-workflows']
  },
  {
    id: generateId(),
    title: 'Node.js 事件循环',
    content: 'Node.js 事件循环分为六个阶段：timers、pending callbacks、idle/prepare、poll、check、close callbacks。setTimeout 在 timers 阶段执行，setImmediate 在 check 阶段执行。',
    source: 'Node.js Docs',
    tags: ['node.js', '事件循环', '异步'],
    category: '后端开发',
    createdAt: now,
    updatedAt: now,
    importance: 9,
    references: ['https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/']
  },
  {
    id: generateId(),
    title: 'Express 中间件顺序',
    content: 'Express 中间件按定义顺序执行。路由匹配后不再继续执行后续中间件。使用 next() 调用下一个中间件。错误处理中间件需要四个参数 (err, req, res, next)。',
    source: 'Express Docs',
    tags: ['express', '中间件', 'node.js'],
    category: '后端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://expressjs.com/en/guide/using-middleware.html']
  },
  {
    id: generateId(),
    title: 'RESTful API 设计原则',
    content: 'RESTful API 使用 HTTP 方法表示操作：GET 获取、POST 创建、PUT 更新、DELETE 删除。资源使用名词复数。状态码使用标准 HTTP 状态码。版本化通过 URL 或 Accept 头实现。',
    source: 'REST API Tutorial',
    tags: ['api', 'rest', '设计'],
    category: '后端开发',
    createdAt: now,
    updatedAt: now,
    importance: 9,
    references: ['https://restfulapi.net/']
  },
  {
    id: generateId(),
    title: 'JWT 认证流程',
    content: 'JWT 认证流程：用户登录获取 token，后续请求在 Authorization 头携带 Bearer token。服务端验证签名和过期时间。JWT 包含 header、payload、signature 三部分，使用 base64url 编码。',
    source: 'JWT.io',
    tags: ['jwt', '认证', '安全'],
    category: '安全',
    createdAt: now,
    updatedAt: now,
    importance: 9,
    references: ['https://jwt.io/introduction']
  },
  {
    id: generateId(),
    title: 'OAuth2.0 授权码流程',
    content: 'OAuth2.0 授权码流程：用户重定向到授权服务器，获取授权码，交换令牌，使用令牌访问资源。适用于服务端应用，安全性最高。',
    source: 'OAuth.net',
    tags: ['oauth', '认证', '安全'],
    category: '安全',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://oauth.net/2/grant-types/authorization-code/']
  },
  {
    id: generateId(),
    title: 'MySQL 索引优化',
    content: 'MySQL 索引使用 B+Tree 结构。合理创建索引可以大幅提升查询性能。避免在大表上创建过多索引。复合索引遵循最左前缀原则。使用 EXPLAIN 分析查询计划。',
    source: 'MySQL Docs',
    tags: ['mysql', '索引', '性能优化'],
    category: '数据库',
    createdAt: now,
    updatedAt: now,
    importance: 9,
    references: ['https://dev.mysql.com/doc/refman/8.0/en/optimization-indexes.html']
  },
  {
    id: generateId(),
    title: 'Redis 缓存策略',
    content: 'Redis 常用缓存策略：Cache-Aside、Write-Through、Write-Behind。使用 TTL 设置过期时间。设置合理的淘汰策略：LRU、LFU、Random。避免缓存穿透、缓存击穿、缓存雪崩问题。',
    source: 'Redis Docs',
    tags: ['redis', '缓存', '性能优化'],
    category: '数据库',
    createdAt: now,
    updatedAt: now,
    importance: 9,
    references: ['https://redis.io/docs/manual/eviction/']
  },
  {
    id: generateId(),
    title: 'MongoDB 查询优化',
    content: 'MongoDB 使用索引加速查询。使用 explain() 分析查询性能。复合索引遵循前缀原则。使用投影减少返回字段。避免全集合扫描。适当使用聚合管道。',
    source: 'MongoDB Docs',
    tags: ['mongodb', '查询优化', '数据库'],
    category: '数据库',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://www.mongodb.com/docs/manual/tutorial/optimize-query-performance/']
  },
  {
    id: generateId(),
    title: 'Docker 镜像分层',
    content: 'Docker 镜像采用分层存储。每层只读，容器在顶层添加可写层。使用多阶段构建减小镜像体积。合理使用 .dockerignore 文件排除不必要文件。',
    source: 'Docker Docs',
    tags: ['docker', '镜像', 'devops'],
    category: 'DevOps',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://docs.docker.com/storage/storagedriver/']
  },
  {
    id: generateId(),
    title: 'Kubernetes Pod 生命周期',
    content: 'Kubernetes Pod 生命周期包括 Pending、Running、Succeeded、Failed、Unknown 阶段。使用 init containers 在主容器启动前执行初始化。探针包括 liveness、readiness、startup。',
    source: 'Kubernetes Docs',
    tags: ['kubernetes', 'pod', 'devops'],
    category: 'DevOps',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/']
  },
  {
    id: generateId(),
    title: 'CI/CD 流水线设计',
    content: 'CI/CD 流水线通常包含：构建、测试、代码质量检查、部署阶段。使用并行任务加速构建。设置合适的缓存策略。使用矩阵构建测试多环境。',
    source: 'GitHub Actions',
    tags: ['ci/cd', 'github actions', 'devops'],
    category: 'DevOps',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://docs.github.com/en/actions/using-workflows']
  },
  {
    id: generateId(),
    title: '微服务架构设计原则',
    content: '微服务架构设计原则：单一职责、自治性、无状态、API 优先、去中心化数据管理。使用服务发现和负载均衡。实现断路器模式处理故障。',
    source: 'Microservices.io',
    tags: ['微服务', '架构', '设计模式'],
    category: '架构设计',
    createdAt: now,
    updatedAt: now,
    importance: 9,
    references: ['https://microservices.io/patterns/index.html']
  },
  {
    id: generateId(),
    title: '设计模式：工厂模式',
    content: '工厂模式通过工厂方法创建对象，隐藏实例化逻辑。简单工厂、工厂方法、抽象工厂三种变体。适用于对象创建复杂或需要解耦的场景。',
    source: 'Refactoring Guru',
    tags: ['设计模式', '工厂模式', 'oop'],
    category: '架构设计',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://refactoring.guru/design-patterns/factory-method']
  },
  {
    id: generateId(),
    title: '设计模式：观察者模式',
    content: '观察者模式定义对象间一对多依赖，当主题状态变化时自动通知所有观察者。适用于事件系统、消息通知等场景。',
    source: 'Refactoring Guru',
    tags: ['设计模式', '观察者模式', 'oop'],
    category: '架构设计',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://refactoring.guru/design-patterns/observer']
  },
  {
    id: generateId(),
    title: '设计模式：策略模式',
    content: '策略模式定义算法家族，封装每个算法，使它们可以互换。运行时动态选择算法。适用于需要多种算法变体的场景。',
    source: 'Refactoring Guru',
    tags: ['设计模式', '策略模式', 'oop'],
    category: '架构设计',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://refactoring.guru/design-patterns/strategy']
  },
  {
    id: generateId(),
    title: '前端性能优化：代码分割',
    content: '代码分割通过动态 import() 实现按需加载，减小首屏体积。Webpack 和 Vite 都支持。React 使用 React.lazy 和 Suspense。Vue 使用 defineAsyncComponent。',
    source: 'Webpack Docs',
    tags: ['性能优化', '代码分割', '前端'],
    category: '性能优化',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://webpack.js.org/guides/code-splitting/']
  },
  {
    id: generateId(),
    title: '前端性能优化：图片优化',
    content: '图片优化策略：使用现代格式 WebP/AVIF；响应式图片使用 srcset 和 sizes；懒加载使用 loading="lazy"；压缩图片；使用 CDN 加速。',
    source: 'Web.dev',
    tags: ['性能优化', '图片', '前端'],
    category: '性能优化',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://web.dev/fast/optimize-images/']
  },
  {
    id: generateId(),
    title: '前端性能优化：缓存策略',
    content: '浏览器缓存策略：使用 Cache-Control 设置缓存过期；ETag 和 Last-Modified 实现协商缓存；Service Worker 实现离线缓存；HTTP/2 多路复用。',
    source: 'Web.dev',
    tags: ['性能优化', '缓存', '前端'],
    category: '性能优化',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://web.dev/http-cache/']
  },
  {
    id: generateId(),
    title: 'XSS 攻击防护',
    content: 'XSS 防护措施：对用户输入进行转义；使用安全的 DOM API；设置 CSP 策略；使用 HttpOnly 和 Secure Cookie；避免使用 eval()。',
    source: 'OWASP',
    tags: ['安全', 'xss', '防护'],
    category: '安全',
    createdAt: now,
    updatedAt: now,
    importance: 9,
    references: ['https://owasp.org/www-community/attacks/xss/']
  },
  {
    id: generateId(),
    title: 'CSRF 攻击防护',
    content: 'CSRF 防护措施：使用 CSRF Token；验证 Referer 头；使用 SameSite Cookie；对敏感操作使用 POST 方法。',
    source: 'OWASP',
    tags: ['安全', 'csrf', '防护'],
    category: '安全',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://owasp.org/www-community/attacks/csrf']
  },
  {
    id: generateId(),
    title: 'SQL 注入防护',
    content: 'SQL 注入防护措施：使用参数化查询/预编译语句；使用 ORM 框架；对用户输入进行验证和过滤；最小化数据库用户权限。',
    source: 'OWASP',
    tags: ['安全', 'sql注入', '防护'],
    category: '安全',
    createdAt: now,
    updatedAt: now,
    importance: 9,
    references: ['https://owasp.org/www-community/attacks/SQL_Injection']
  },
  {
    id: generateId(),
    title: 'Jest Mock 函数',
    content: 'Jest Mock 函数用于模拟依赖。使用 jest.fn() 创建模拟函数；使用 jest.mock() 模拟模块；使用 .mockReturnValue() 设置返回值；使用 .toHaveBeenCalled() 断言调用。',
    source: 'Jest Docs',
    tags: ['jest', '测试', 'mock'],
    category: '测试',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://jestjs.io/docs/mock-functions']
  },
  {
    id: generateId(),
    title: '测试金字塔',
    content: '测试金字塔包含三层：单元测试（底层，数量最多）、集成测试（中层）、端到端测试（顶层，数量最少）。合理分配测试类型可以提高效率和可靠性。',
    source: 'Martin Fowler',
    tags: ['测试', '单元测试', '集成测试'],
    category: '测试',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://martinfowler.com/articles/practical-test-pyramid.html']
  },
  {
    id: generateId(),
    title: 'TDD 测试驱动开发',
    content: 'TDD 流程：先写失败的测试，再写通过测试的最小代码，最后重构。红-绿-重构循环。优点：更好的测试覆盖率，更清晰的设计。',
    source: 'Martin Fowler',
    tags: ['测试', 'tdd', '开发流程'],
    category: '测试',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://martinfowler.com/bliki/TestDrivenDevelopment.html']
  },
  {
    id: generateId(),
    title: 'ESLint 配置',
    content: 'ESLint 使用配置文件（.eslintrc）管理规则。extends 继承预设配置；rules 自定义规则；plugins 添加额外规则。使用 --fix 自动修复问题。',
    source: 'ESLint Docs',
    tags: ['eslint', '工具链', '代码质量'],
    category: '工具链',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://eslint.org/docs/user-guide/configuring/']
  },
  {
    id: generateId(),
    title: 'Prettier 配置',
    content: 'Prettier 使用 .prettierrc 配置格式化规则。printWidth 设置换行宽度；tabWidth 设置缩进；semi 是否加分号；singleQuote 是否使用单引号。',
    source: 'Prettier Docs',
    tags: ['prettier', '工具链', '代码格式化'],
    category: '工具链',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://prettier.io/docs/en/configuration.html']
  },
  {
    id: generateId(),
    title: 'pnpm 工作区',
    content: 'pnpm 使用 workspace 管理多包项目。在根目录创建 pnpm-workspace.yaml，定义 packages 路径。使用 pnpm add --workspace 添加依赖。共享依赖提升到根 node_modules。',
    source: 'pnpm Docs',
    tags: ['pnpm', '工具链', 'monorepo'],
    category: '工具链',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://pnpm.io/workspaces']
  },
  {
    id: generateId(),
    title: 'Solid 原则',
    content: 'SOLID 原则包括：单一职责、开闭原则、里氏替换、接口隔离、依赖倒置。遵循这些原则可以提高代码的可维护性和可扩展性。',
    source: 'Robert Martin',
    tags: ['solid', '设计原则', '最佳实践'],
    category: '最佳实践',
    createdAt: now,
    updatedAt: now,
    importance: 9,
    references: ['https://en.wikipedia.org/wiki/SOLID']
  },
  {
    id: generateId(),
    title: 'Clean Code 原则',
    content: 'Clean Code 原则：有意义的命名、保持函数短小、避免重复代码、使用描述性变量名、注释解释为什么而非怎么做。可读性比性能更重要。',
    source: 'Robert Martin',
    tags: ['clean code', '代码质量', '最佳实践'],
    category: '最佳实践',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://www.oreilly.com/library/view/clean-code/9780136083238/']
  },
  {
    id: generateId(),
    title: '代码审查检查清单',
    content: '代码审查要点：逻辑正确性、代码风格、性能考虑、安全隐患、错误处理、文档注释、测试覆盖、命名规范。使用检查清单确保审查质量。',
    source: 'Google',
    tags: ['代码审查', '最佳实践', '团队协作'],
    category: '最佳实践',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://google.github.io/eng-practices/review/checklist/']
  },
  {
    id: generateId(),
    title: 'React Context 使用',
    content: 'React Context 用于跨组件传递数据，避免 props 层层传递。创建 Context 使用 createContext()；提供值使用 Provider；消费值使用 useContext() 或 Consumer。',
    source: 'React Docs',
    tags: ['react', 'context', '状态管理'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://react.dev/reference/react/createContext']
  },
  {
    id: generateId(),
    title: 'React useReducer Hook',
    content: 'useReducer 用于管理复杂状态逻辑。接收 reducer 函数和初始状态，返回状态和 dispatch 函数。reducer 是纯函数，根据 action 更新状态。',
    source: 'React Docs',
    tags: ['react', 'hooks', 'usereducer', '状态管理'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://react.dev/reference/react/useReducer']
  },
  {
    id: generateId(),
    title: 'TypeScript 类型守卫',
    content: '类型守卫用于在运行时缩小类型范围。typeof 检查基本类型；instanceof 检查类实例；in 检查属性存在；自定义类型守卫使用 is 关键字。',
    source: 'TypeScript Docs',
    tags: ['typescript', '类型守卫', '类型'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://www.typescriptlang.org/docs/handbook/2/narrowing.html']
  },
  {
    id: generateId(),
    title: 'TypeScript 条件类型',
    content: '条件类型根据类型关系选择类型。语法：T extends U ? X : Y。常用工具类型如 ReturnType、Parameters、Exclude、Extract 都是条件类型实现。',
    source: 'TypeScript Docs',
    tags: ['typescript', '条件类型', '高级类型'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://www.typescriptlang.org/docs/handbook/2/conditional-types.html']
  },
  {
    id: generateId(),
    title: 'Vue3 provide/inject',
    content: 'provide/inject 用于跨层级组件通信。父组件使用 provide 提供值，子孙组件使用 inject 注入值。适用于深度嵌套场景。',
    source: 'Vue Docs',
    tags: ['vue', 'provide', 'inject', '组件通信'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://vuejs.org/api/component-options.html#provide']
  },
  {
    id: generateId(),
    title: 'Vue3 watch 和 watchEffect',
    content: 'watch 需要明确指定依赖，只在依赖变化时执行。watchEffect 自动追踪依赖，在初始化时立即执行。watch 可以访问旧值和新值。',
    source: 'Vue Docs',
    tags: ['vue', 'watch', '响应式'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://vuejs.org/api/reactivity-core.html#watch']
  },
  {
    id: generateId(),
    title: 'JavaScript 闭包',
    content: '闭包是函数能够访问其词法作用域外的变量。创建闭包的方式：返回内部函数、传递函数作为参数。闭包常用于数据封装和函数柯里化。',
    source: 'MDN',
    tags: ['javascript', '闭包', '基础'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures']
  },
  {
    id: generateId(),
    title: 'JavaScript 事件委托',
    content: '事件委托利用事件冒泡，将事件处理程序绑定到父元素而非每个子元素。减少内存占用，支持动态添加元素。使用 event.target 判断触发元素。',
    source: 'MDN',
    tags: ['javascript', '事件委托', 'dom'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_delegation']
  },
  {
    id: generateId(),
    title: 'CSS 伪元素 ::before 和 ::after',
    content: '::before 和 ::after 创建元素的子伪元素。必须设置 content 属性。常用于添加装饰性内容、清除浮动、创建图标。',
    source: 'MDN',
    tags: ['css', '伪元素', '样式'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://developer.mozilla.org/en-US/docs/Web/CSS/::before']
  },
  {
    id: generateId(),
    title: 'CSS 媒体查询',
    content: '媒体查询用于响应式设计。语法：@media (条件) { 样式 }。常用条件：max-width、min-width、orientation。使用移动优先或桌面优先策略。',
    source: 'MDN',
    tags: ['css', '媒体查询', '响应式'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries']
  },
  {
    id: generateId(),
    title: 'Git Rebase 与 Merge',
    content: 'Merge 保留完整历史，创建合并提交。Rebase 将提交移动到新的基础上，产生线性历史。本地分支使用 rebase，公共分支使用 merge。',
    source: 'Git Docs',
    tags: ['git', 'rebase', 'merge'],
    category: '工具链',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://git-scm.com/docs/git-rebase']
  },
  {
    id: generateId(),
    title: 'Node.js Stream',
    content: 'Stream 用于处理大量数据，避免一次性加载到内存。四种类型：Readable、Writable、Duplex、Transform。使用 pipe() 连接流。',
    source: 'Node.js Docs',
    tags: ['node.js', 'stream', '性能'],
    category: '后端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://nodejs.org/docs/latest/api/stream.html']
  },
  {
    id: generateId(),
    title: 'Express 错误处理',
    content: 'Express 错误处理中间件需要四个参数 (err, req, res, next)。使用 try/catch 捕获同步错误。异步错误需要调用 next(err)。设置统一的错误响应格式。',
    source: 'Express Docs',
    tags: ['express', '错误处理', 'node.js'],
    category: '后端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://expressjs.com/en/guide/error-handling.html']
  },
  {
    id: generateId(),
    title: 'GraphQL 与 REST 对比',
    content: 'REST 使用多个端点获取不同资源，GraphQL 使用单一端点按需获取数据。GraphQL 减少过度获取和多次请求，但需要额外的学习成本和缓存策略。',
    source: 'GraphQL Docs',
    tags: ['graphql', 'api', 'rest'],
    category: '后端开发',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://graphql.org/learn/']
  },
  {
    id: generateId(),
    title: 'Cookie 安全标志',
    content: 'Cookie 安全标志：HttpOnly 防止 JS 访问；Secure 只在 HTTPS 传输；SameSite 防止 CSRF；Max-Age 设置过期时间。',
    source: 'OWASP',
    tags: ['安全', 'cookie', 'http'],
    category: '安全',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://owasp.org/www-community/attacks/csrf']
  },
  {
    id: generateId(),
    title: 'HTTPS 证书管理',
    content: 'HTTPS 使用 TLS/SSL 证书加密通信。使用 Let\'s Encrypt 获取免费证书。定期更新证书。配置正确的 TLS 版本和加密套件。',
    source: 'Let\'s Encrypt',
    tags: ['安全', 'https', 'tls'],
    category: '安全',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://letsencrypt.org/']
  },
  {
    id: generateId(),
    title: 'MySQL 事务隔离级别',
    content: 'MySQL 事务隔离级别：READ UNCOMMITTED（脏读）、READ COMMITTED（不可重复读）、REPEATABLE READ（幻读）、SERIALIZABLE。InnoDB 默认 REPEATABLE READ。',
    source: 'MySQL Docs',
    tags: ['mysql', '事务', '数据库'],
    category: '数据库',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://dev.mysql.com/doc/refman/8.0/en/innodb-transaction-isolation-levels.html']
  },
  {
    id: generateId(),
    title: 'Redis 数据类型',
    content: 'Redis 支持五种基本数据类型：String（字符串）、Hash（哈希）、List（列表）、Set（集合）、ZSet（有序集合）。选择合适的数据类型可以提高效率。',
    source: 'Redis Docs',
    tags: ['redis', '数据类型', '数据库'],
    category: '数据库',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://redis.io/docs/data-types/']
  },
  {
    id: generateId(),
    title: 'MongoDB 副本集',
    content: 'MongoDB 副本集提供高可用性。包含一个主节点（Primary）和多个从节点（Secondary）。主节点处理写操作，从节点复制数据。故障时自动选举新主节点。',
    source: 'MongoDB Docs',
    tags: ['mongodb', '副本集', '高可用'],
    category: '数据库',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://www.mongodb.com/docs/manual/replication/']
  },
  {
    id: generateId(),
    title: 'Docker Compose',
    content: 'Docker Compose 使用 YAML 文件定义多容器应用。services 定义服务；volumes 定义卷；networks 定义网络。使用 docker-compose up 启动应用。',
    source: 'Docker Docs',
    tags: ['docker', 'compose', 'devops'],
    category: 'DevOps',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://docs.docker.com/compose/']
  },
  {
    id: generateId(),
    title: 'Kubernetes Service',
    content: 'Kubernetes Service 提供 Pod 的稳定访问地址。ClusterIP 内部访问；NodePort 暴露到节点端口；LoadBalancer 云厂商负载均衡；ExternalName 映射外部服务。',
    source: 'Kubernetes Docs',
    tags: ['kubernetes', 'service', 'devops'],
    category: 'DevOps',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://kubernetes.io/docs/concepts/services-networking/service/']
  },
  {
    id: generateId(),
    title: 'Nginx 反向代理',
    content: 'Nginx 反向代理接收客户端请求，转发到后端服务器。配置 upstream 定义后端服务器组。使用 location 匹配 URL。支持负载均衡和缓存。',
    source: 'Nginx Docs',
    tags: ['nginx', '反向代理', 'devops'],
    category: 'DevOps',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://nginx.org/en/docs/http/ngx_http_proxy_module.html']
  },
  {
    id: generateId(),
    title: '设计模式：单例模式',
    content: '单例模式确保类只有一个实例。实现方式：私有构造函数、静态获取方法。注意线程安全问题。适用于全局状态管理、日志器等场景。',
    source: 'Refactoring Guru',
    tags: ['设计模式', '单例模式', 'oop'],
    category: '架构设计',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://refactoring.guru/design-patterns/singleton']
  },
  {
    id: generateId(),
    title: '设计模式：适配器模式',
    content: '适配器模式将一个类的接口转换成客户端期望的另一个接口。适用于集成已有代码或第三方库。分为类适配器和对象适配器。',
    source: 'Refactoring Guru',
    tags: ['设计模式', '适配器模式', 'oop'],
    category: '架构设计',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://refactoring.guru/design-patterns/adapter']
  },
  {
    id: generateId(),
    title: '设计模式：装饰器模式',
    content: '装饰器模式动态给对象添加额外功能。使用组合而非继承。适用于需要灵活扩展功能的场景。',
    source: 'Refactoring Guru',
    tags: ['设计模式', '装饰器模式', 'oop'],
    category: '架构设计',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://refactoring.guru/design-patterns/decorator']
  },
  {
    id: generateId(),
    title: '前端性能优化：首屏优化',
    content: '首屏优化策略：减小 HTML 体积；内联关键 CSS；使用 Critical CSS；预加载关键资源；延迟加载非关键资源；使用 CDN。',
    source: 'Web.dev',
    tags: ['性能优化', '首屏', '前端'],
    category: '性能优化',
    createdAt: now,
    updatedAt: now,
    importance: 9,
    references: ['https://web.dev/fast/']
  },
  {
    id: generateId(),
    title: '前端性能优化：内存泄漏',
    content: '常见内存泄漏原因：意外的全局变量、闭包引用、DOM 引用未清理、定时器未清除、事件监听器未移除。使用 Chrome DevTools Memory 面板检测。',
    source: 'Web.dev',
    tags: ['性能优化', '内存泄漏', '前端'],
    category: '性能优化',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://developer.chrome.com/docs/devtools/memory-problems/']
  },
  {
    id: generateId(),
    title: '前端性能优化：Web Worker',
    content: 'Web Worker 在后台线程执行脚本，不阻塞主线程。适用于计算密集型任务。使用 postMessage 通信。注意不能访问 DOM。',
    source: 'MDN',
    tags: ['性能优化', 'web worker', '前端'],
    category: '性能优化',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API']
  },
  {
    id: generateId(),
    title: '安全：依赖漏洞检测',
    content: '依赖漏洞检测工具：npm audit、Snyk、Dependabot。定期更新依赖。设置自动化检测。关注安全公告。',
    source: 'npm',
    tags: ['安全', '依赖', '漏洞'],
    category: '安全',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://docs.npmjs.com/cli/v9/commands/npm-audit']
  },
  {
    id: generateId(),
    title: '安全：输入验证',
    content: '输入验证策略：服务端验证为主，客户端验证为辅。使用白名单验证。对特殊字符进行转义。使用验证库如 Joi、Zod。',
    source: 'OWASP',
    tags: ['安全', '输入验证', '防护'],
    category: '安全',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://owasp.org/www-community/attacks/Input_Validation']
  },
  {
    id: generateId(),
    title: 'Vitest 测试框架',
    content: 'Vitest 是新一代测试框架，与 Vite 无缝集成。支持 ESM 原生模块。内置 TypeScript 支持。运行速度快。兼容 Jest API。',
    source: 'Vitest Docs',
    tags: ['vitest', '测试', '工具链'],
    category: '测试',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://vitest.dev/']
  },
  {
    id: generateId(),
    title: 'Cypress E2E 测试',
    content: 'Cypress 是端到端测试框架。直接在浏览器中运行。自动等待元素出现。内置网络请求拦截。提供时间旅行调试。',
    source: 'Cypress Docs',
    tags: ['cypress', 'e2e', '测试'],
    category: '测试',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://docs.cypress.io/']
  },
  {
    id: generateId(),
    title: 'npm 脚本使用',
    content: 'npm 脚本定义在 package.json 的 scripts 字段。使用 npm run <script> 执行。支持预/post 钩子（prebuild、postbuild）。可以使用 && 连接多个命令。',
    source: 'npm Docs',
    tags: ['npm', '脚本', '工具链'],
    category: '工具链',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://docs.npmjs.com/cli/v9/using-npm/scripts']
  },
  {
    id: generateId(),
    title: 'Babel 配置',
    content: 'Babel 将 ES6+ 代码转译为兼容代码。使用 @babel/preset-env 自动根据目标环境选择转换。使用插件添加特定功能。配置文件可以是 .babelrc 或 babel.config.json。',
    source: 'Babel Docs',
    tags: ['babel', '工具链', '转译'],
    category: '工具链',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://babeljs.io/docs/en/configuration']
  },
  {
    id: generateId(),
    title: '代码重构技巧',
    content: '重构技巧：提取函数、提取变量、拆分长函数、消除重复代码、简化条件判断、重命名变量和函数。每次小步修改，确保测试通过。',
    source: 'Refactoring',
    tags: ['重构', '最佳实践', '代码质量'],
    category: '最佳实践',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://refactoring.guru/']
  },
  {
    id: generateId(),
    title: '代码注释规范',
    content: '注释规范：函数注释使用 JSDoc/TSDoc；行内注释解释复杂逻辑；避免冗余注释；TODO 标记待完成任务；FIXME 标记需要修复的问题。',
    source: 'Google',
    tags: ['注释', '最佳实践', '代码质量'],
    category: '最佳实践',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://google.github.io/styleguide/']
  },
  {
    id: generateId(),
    title: 'React 自定义 Hook',
    content: '自定义 Hook 以 use 开头，封装可复用逻辑。可以调用其他 Hook。返回值灵活，可以是数组或对象。例如 useFetch、useLocalStorage。',
    source: 'React Docs',
    tags: ['react', 'hooks', '自定义hook'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://react.dev/reference/react#custom-hooks']
  },
  {
    id: generateId(),
    title: 'React 性能优化：React.memo',
    content: 'React.memo 是高阶组件，对组件的 props 进行浅比较，避免不必要的重渲染。适用于纯展示组件。配合 useMemo 和 useCallback 使用效果更好。',
    source: 'React Docs',
    tags: ['react', '性能优化', 'memo'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://react.dev/reference/react/memo']
  },
  {
    id: generateId(),
    title: 'TypeScript 接口与类型别名',
    content: '接口使用 interface 定义，类型别名使用 type 定义。接口可以扩展和合并声明，类型别名可以表示联合类型和交叉类型。推荐优先使用接口。',
    source: 'TypeScript Docs',
    tags: ['typescript', 'interface', 'type'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://www.typescriptlang.org/docs/handbook/2/everyday-types.html']
  },
  {
    id: generateId(),
    title: 'TypeScript 类型断言',
    content: '类型断言告诉编译器某个值的类型。使用 as 语法：value as Type。使用尖括号语法：<Type>value（JSX 中不适用）。避免过度使用，优先使用类型守卫。',
    source: 'TypeScript Docs',
    tags: ['typescript', '类型断言', '类型'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions']
  },
  {
    id: generateId(),
    title: 'Vue3 组合式函数',
    content: '组合式函数以 use 开头，封装可复用逻辑。可以调用其他组合式函数和响应式 API。返回响应式状态和方法。例如 useMouse、useFetch。',
    source: 'Vue Docs',
    tags: ['vue', 'composition', '组合式函数'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://vuejs.org/guide/reusability/composables.html']
  },
  {
    id: generateId(),
    title: 'Vue3 自定义指令',
    content: '自定义指令使用 defineDirective 定义。支持 mounted、updated、unmounted 钩子。可以接收参数和修饰符。适用于 DOM 操作场景。',
    source: 'Vue Docs',
    tags: ['vue', '指令', '自定义'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://vuejs.org/guide/reusability/custom-directives.html']
  },
  {
    id: generateId(),
    title: 'JavaScript Promise.all 与 Promise.allSettled',
    content: 'Promise.all 所有 Promise 成功才成功，任一失败则全部失败。Promise.allSettled 等待所有 Promise 完成，返回每个的结果状态（fulfilled/rejected）。',
    source: 'MDN',
    tags: ['javascript', 'promise', 'async'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all']
  },
  {
    id: generateId(),
    title: 'JavaScript 可选链和空值合并',
    content: '可选链 ?. 安全访问嵌套属性，避免空值错误。空值合并 ?? 仅在值为 null 或 undefined 时返回默认值。组合使用：obj?.prop ?? defaultValue。',
    source: 'MDN',
    tags: ['javascript', '可选链', '空值合并'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining']
  },
  {
    id: generateId(),
    title: 'CSS 变量',
    content: 'CSS 变量使用 -- 定义，var() 使用。可以在 :root 中定义全局变量。支持继承和级联。可以通过 JavaScript 动态修改。',
    source: 'MDN',
    tags: ['css', '变量', '样式'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties']
  },
  {
    id: generateId(),
    title: 'CSS Flexbox gap 属性',
    content: 'gap 属性设置 flex 子元素之间的间距。row-gap 设置行间距，column-gap 设置列间距。gap 是简写形式。适用于 Flexbox 和 Grid。',
    source: 'MDN',
    tags: ['css', 'flexbox', 'gap'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://developer.mozilla.org/en-US/docs/Web/CSS/gap']
  },
  {
    id: generateId(),
    title: 'Git 工作流：GitHub Flow',
    content: 'GitHub Flow 简化的分支策略：从 main 分支创建 feature 分支，提交更改，创建 Pull Request，审查通过后合并回 main。适用于持续部署场景。',
    source: 'GitHub',
    tags: ['git', '工作流', 'github flow'],
    category: '工具链',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://docs.github.com/en/get-started/quickstart/github-flow']
  },
  {
    id: generateId(),
    title: 'Node.js 模块化',
    content: 'Node.js 支持 CommonJS 和 ES Modules。使用 require() 和 module.exports 是 CommonJS；使用 import 和 export 是 ES Modules。package.json 中设置 "type": "module" 使用 ES Modules。',
    source: 'Node.js Docs',
    tags: ['node.js', '模块化', 'commonjs'],
    category: '后端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://nodejs.org/docs/latest/api/modules.html']
  },
  {
    id: generateId(),
    title: 'Express 路由参数',
    content: 'Express 路由参数使用 :param 定义。通过 req.params 访问。支持正则表达式约束。例如 /users/:id([0-9]+) 只匹配数字 ID。',
    source: 'Express Docs',
    tags: ['express', '路由', 'node.js'],
    category: '后端开发',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://expressjs.com/en/guide/routing.html']
  },
  {
    id: generateId(),
    title: 'REST API 分页设计',
    content: '分页策略：基于偏移量（offset/limit）或基于游标（cursor）。偏移量简单但大数据量时性能差。游标分页使用唯一标识，性能更好。返回 total、page、perPage 等元数据。',
    source: 'REST API Tutorial',
    tags: ['api', '分页', '设计'],
    category: '后端开发',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://restfulapi.net/pagination/']
  },
  {
    id: generateId(),
    title: '安全：CORS 配置',
    content: 'CORS（跨域资源共享）控制浏览器是否允许跨域请求。服务端设置 Access-Control-Allow-Origin、Access-Control-Allow-Methods、Access-Control-Allow-Headers。使用预检请求（OPTIONS）。',
    source: 'MDN',
    tags: ['安全', 'cors', '跨域'],
    category: '安全',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS']
  },
  {
    id: generateId(),
    title: '安全：速率限制',
    content: '速率限制防止 API 被滥用。使用中间件如 express-rate-limit。限制请求频率（如每分钟 100 次）。使用 Redis 存储跨实例的请求计数。',
    source: 'OWASP',
    tags: ['安全', '速率限制', 'api'],
    category: '安全',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://owasp.org/www-community/attacks/Denial_of_Service']
  },
  {
    id: generateId(),
    title: 'MySQL 锁机制',
    content: 'MySQL 锁包括表级锁和行级锁。InnoDB 使用行级锁，MyISAM 使用表级锁。行级锁基于索引。死锁可能发生在交叉更新场景。使用 SHOW PROCESSLIST 查看锁状态。',
    source: 'MySQL Docs',
    tags: ['mysql', '锁', '数据库'],
    category: '数据库',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://dev.mysql.com/doc/refman/8.0/en/innodb-locking.html']
  },
  {
    id: generateId(),
    title: 'Redis 事务',
    content: 'Redis 事务使用 MULTI、EXEC、DISCARD 命令。MULTI 开始事务，EXEC 执行，DISCARD 取消。Redis 事务保证原子性但不支持回滚。使用 WATCH 监控键变化。',
    source: 'Redis Docs',
    tags: ['redis', '事务', '数据库'],
    category: '数据库',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://redis.io/docs/manual/transactions/']
  },
  {
    id: generateId(),
    title: 'MongoDB 聚合管道',
    content: 'MongoDB 聚合管道由多个阶段组成：$match（过滤）、$group（分组）、$project（投影）、$sort（排序）、$limit（限制）。阶段按顺序执行，前一阶段的输出作为后一阶段的输入。',
    source: 'MongoDB Docs',
    tags: ['mongodb', '聚合', '数据库'],
    category: '数据库',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://www.mongodb.com/docs/manual/aggregation/']
  },
  {
    id: generateId(),
    title: 'Docker 多阶段构建',
    content: '多阶段构建使用多个 FROM 指令。第一阶段构建应用，第二阶段复制产物。减小最终镜像体积。示例：builder 阶段编译，runtime 阶段运行。',
    source: 'Docker Docs',
    tags: ['docker', '多阶段构建', 'devops'],
    category: 'DevOps',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://docs.docker.com/build/building/multi-stage/']
  },
  {
    id: generateId(),
    title: 'Kubernetes ConfigMap 和 Secret',
    content: 'ConfigMap 存储非敏感配置，Secret 存储敏感信息（如密码、API Key）。Secret 使用 Base64 编码。通过 volume 或环境变量注入到 Pod。',
    source: 'Kubernetes Docs',
    tags: ['kubernetes', 'configmap', 'secret'],
    category: 'DevOps',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://kubernetes.io/docs/concepts/configuration/configmap/']
  },
  {
    id: generateId(),
    title: 'Prometheus 监控',
    content: 'Prometheus 是开源监控系统。使用指标（metrics）收集数据。支持四种指标类型：Counter（计数器）、Gauge（仪表盘）、Histogram（直方图）、Summary（摘要）。使用 Grafana 可视化。',
    source: 'Prometheus Docs',
    tags: ['prometheus', '监控', 'devops'],
    category: 'DevOps',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://prometheus.io/docs/introduction/overview/']
  },
  {
    id: generateId(),
    title: '设计模式：策略模式实现',
    content: '策略模式实现：定义策略接口，实现多个策略类，上下文类持有策略引用。运行时切换策略。适用于支付方式、排序算法等场景。',
    source: 'Refactoring Guru',
    tags: ['设计模式', '策略模式', '实现'],
    category: '架构设计',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://refactoring.guru/design-patterns/strategy/typescript/example']
  },
  {
    id: generateId(),
    title: '设计模式：模板方法模式',
    content: '模板方法模式定义算法骨架，子类实现具体步骤。抽象类定义模板方法和抽象方法。适用于框架设计、算法变体场景。',
    source: 'Refactoring Guru',
    tags: ['设计模式', '模板方法', 'oop'],
    category: '架构设计',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://refactoring.guru/design-patterns/template-method']
  },
  {
    id: generateId(),
    title: '设计模式：状态模式',
    content: '状态模式封装对象状态，使对象行为随状态变化而变化。状态类实现状态接口，上下文类委托给当前状态对象。适用于有限状态机场景。',
    source: 'Refactoring Guru',
    tags: ['设计模式', '状态模式', 'oop'],
    category: '架构设计',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://refactoring.guru/design-patterns/state']
  },
  {
    id: generateId(),
    title: '前端性能优化：Lazy Loading',
    content: '懒加载延迟加载非关键资源。图片使用 loading="lazy" 属性。组件使用 React.lazy 或 Vue 的 defineAsyncComponent。路由级别的代码分割。',
    source: 'Web.dev',
    tags: ['性能优化', '懒加载', '前端'],
    category: '性能优化',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://web.dev/lazy-loading/']
  },
  {
    id: generateId(),
    title: '前端性能优化：Code Splitting 实践',
    content: '代码分割实践：路由级别分割、组件级别分割、按需加载第三方库。使用 React.lazy + Suspense。使用 webpackChunkName 命名 chunks。分析打包体积。',
    source: 'Webpack Docs',
    tags: ['性能优化', '代码分割', 'webpack'],
    category: '性能优化',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://webpack.js.org/guides/code-splitting/']
  },
  {
    id: generateId(),
    title: '前端性能优化：Service Worker',
    content: 'Service Worker 在浏览器后台运行。拦截网络请求，实现离线缓存。使用 Cache API 存储资源。使用 Workbox 简化开发。',
    source: 'MDN',
    tags: ['性能优化', 'service worker', 'pwa'],
    category: '性能优化',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API']
  },
  {
    id: generateId(),
    title: '安全：SQL 注入防护实践',
    content: 'SQL 注入防护：使用参数化查询；避免字符串拼接；使用 ORM；输入验证；最小权限原则；使用存储过程时注意安全。',
    source: 'OWASP',
    tags: ['安全', 'sql注入', '实践'],
    category: '安全',
    createdAt: now,
    updatedAt: now,
    importance: 9,
    references: ['https://owasp.org/www-community/attacks/SQL_Injection']
  },
  {
    id: generateId(),
    title: '安全：XSS 防护实践',
    content: 'XSS 防护：转义输出；使用 textContent 而非 innerHTML；设置 CSP；使用 HttpOnly Cookie；过滤用户输入；使用模板引擎自动转义。',
    source: 'OWASP',
    tags: ['安全', 'xss', '实践'],
    category: '安全',
    createdAt: now,
    updatedAt: now,
    importance: 9,
    references: ['https://owasp.org/www-community/attacks/xss/']
  },
  {
    id: generateId(),
    title: '测试覆盖率',
    content: '测试覆盖率指标：语句覆盖率、分支覆盖率、函数覆盖率、行覆盖率。目标不是 100%，而是覆盖关键路径。使用 jest --coverage 或 vitest --coverage 生成报告。',
    source: 'Jest Docs',
    tags: ['测试', '覆盖率', '工具'],
    category: '测试',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://jestjs.io/docs/coverage']
  },
  {
    id: generateId(),
    title: 'Mock 与 Stub',
    content: 'Mock 验证交互行为，Stub 提供预设返回值。Mock 关注"是否调用"，Stub 关注"返回什么"。在测试中合理使用两者。',
    source: 'Martin Fowler',
    tags: ['测试', 'mock', 'stub'],
    category: '测试',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://martinfowler.com/articles/mocksArentStubs.html']
  },
  {
    id: generateId(),
    title: 'npm 依赖管理',
    content: 'npm 依赖管理：使用 ^ 和 ~ 控制版本范围；定期更新依赖（npm update）；使用 npm audit 检测漏洞；使用 pnpm 提升安装速度和节省空间。',
    source: 'npm Docs',
    tags: ['npm', '依赖', '工具链'],
    category: '工具链',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://docs.npmjs.com/cli/v9/commands/npm-install']
  },
  {
    id: generateId(),
    title: 'Git Hooks',
    content: 'Git Hooks 是在特定 Git 事件时执行的脚本。常用钩子：pre-commit（提交前）、commit-msg（提交信息校验）、pre-push（推送前）。使用 Husky 管理钩子。',
    source: 'Git Docs',
    tags: ['git', 'hooks', '工具链'],
    category: '工具链',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://git-scm.com/docs/githooks']
  },
  {
    id: generateId(),
    title: '代码风格指南',
    content: '代码风格指南：统一缩进（空格/制表符）；代码行长度限制；大括号位置；分号使用；变量命名规范（驼峰/下划线）。使用 ESLint 和 Prettier 强制执行。',
    source: 'Google',
    tags: ['代码风格', '最佳实践', '规范'],
    category: '最佳实践',
    createdAt: now,
    updatedAt: now,
    importance: 7,
    references: ['https://google.github.io/styleguide/']
  },
  {
    id: generateId(),
    title: '错误处理最佳实践',
    content: '错误处理：明确错误类型；提供有用的错误信息；使用 try/catch 捕获异常；不要吞掉异常；使用统一的错误处理中间件；记录错误日志。',
    source: 'OWASP',
    tags: ['错误处理', '最佳实践', '调试'],
    category: '最佳实践',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://owasp.org/www-community/Improper_Error_Handling']
  },
  {
    id: generateId(),
    title: 'React useEffect 清理函数',
    content: 'useEffect 返回的函数在组件卸载前执行，用于清理副作用。清理定时器、取消订阅、移除事件监听器。避免内存泄漏。',
    source: 'React Docs',
    tags: ['react', 'hooks', 'useeffect', '清理'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://react.dev/reference/react/useEffect#cleaning-up-an-effect']
  },
  {
    id: generateId(),
    title: 'React useMemo Hook',
    content: 'useMemo 缓存计算结果，避免昂贵计算在每次渲染时重复执行。依赖数组变化时重新计算。用于优化渲染性能。',
    source: 'React Docs',
    tags: ['react', 'hooks', 'usememo', '性能'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://react.dev/reference/react/useMemo']
  },
  {
    id: generateId(),
    title: 'React useCallback Hook',
    content: 'useCallback 缓存函数引用，避免子组件不必要的重渲染。与 React.memo 配合使用效果更好。依赖数组变化时重新创建函数。',
    source: 'React Docs',
    tags: ['react', 'hooks', 'usecallback', '性能'],
    category: '前端开发',
    createdAt: now,
    updatedAt: now,
    importance: 8,
    references: ['https://react.dev/reference/react/useCallback']
  }
];